# Site settings
title: CoDefined
url: "https://popey456963.github.io"
baseurl: "/blog"
description: >
  A 16 year olds blog where he talks about programming, web development
  and living life as a child.  I'm currently working with subjectrefresh.info
  to try to create a better education for all, whilst also providing developer
  tools.
# Your information
email: 
author: Alexander Craggs
avatar: "https://i.imgur.com/z4vT78N.png"
profile: An Avid Programmer.
twitter_username: popey456963
github_username: popey456963

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: codefined   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archive/:title

gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
